-- AlterTable
ALTER TABLE "User" ADD COLUMN "avatarPositionX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "avatarPositionY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "avatarScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
